/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRoomsRouteImport } from './routes/_protected/rooms'
import { Route as ProtectedCatalogRouteImport } from './routes/_protected/catalog'
import { Route as ProtectedRoomIdRouteImport } from './routes/_protected/room.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoomsRoute = ProtectedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedCatalogRoute = ProtectedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedRoomIdRoute = ProtectedRoomIdRouteImport.update({
  id: '/room/$id',
  path: '/room/$id',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof ProtectedCatalogRoute
  '/rooms': typeof ProtectedRoomsRoute
  '/room/$id': typeof ProtectedRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof ProtectedCatalogRoute
  '/rooms': typeof ProtectedRoomsRoute
  '/room/$id': typeof ProtectedRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_protected/catalog': typeof ProtectedCatalogRoute
  '/_protected/rooms': typeof ProtectedRoomsRoute
  '/_protected/room/$id': typeof ProtectedRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/catalog' | '/rooms' | '/room/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/catalog' | '/rooms' | '/room/$id'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/auth'
    | '/_protected/catalog'
    | '/_protected/rooms'
    | '/_protected/room/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/rooms': {
      id: '/_protected/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof ProtectedRoomsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/catalog': {
      id: '/_protected/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof ProtectedCatalogRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/room/$id': {
      id: '/_protected/room/$id'
      path: '/room/$id'
      fullPath: '/room/$id'
      preLoaderRoute: typeof ProtectedRoomIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedCatalogRoute: typeof ProtectedCatalogRoute
  ProtectedRoomsRoute: typeof ProtectedRoomsRoute
  ProtectedRoomIdRoute: typeof ProtectedRoomIdRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedCatalogRoute: ProtectedCatalogRoute,
  ProtectedRoomsRoute: ProtectedRoomsRoute,
  ProtectedRoomIdRoute: ProtectedRoomIdRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
