/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ProtectedDashboardRouteRouteImport } from './routes/_protected/_dashboard/route'
import { Route as PublicJoinCodeRouteImport } from './routes/_public/join.$code'
import { Route as ProtectedRoomIdRouteImport } from './routes/_protected/room.$id'
import { Route as ProtectedDashboardRoomsRouteImport } from './routes/_protected/_dashboard/rooms'
import { Route as ProtectedDashboardCatalogRouteImport } from './routes/_protected/_dashboard/catalog'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ProtectedDashboardRouteRoute = ProtectedDashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const PublicJoinCodeRoute = PublicJoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ProtectedRoomIdRoute = ProtectedRoomIdRouteImport.update({
  id: '/room/$id',
  path: '/room/$id',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardRoomsRoute = ProtectedDashboardRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => ProtectedDashboardRouteRoute,
} as any)
const ProtectedDashboardCatalogRoute =
  ProtectedDashboardCatalogRouteImport.update({
    id: '/catalog',
    path: '/catalog',
    getParentRoute: () => ProtectedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/': typeof PublicIndexRoute
  '/catalog': typeof ProtectedDashboardCatalogRoute
  '/rooms': typeof ProtectedDashboardRoomsRoute
  '/room/$id': typeof ProtectedRoomIdRoute
  '/join/$code': typeof PublicJoinCodeRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof PublicIndexRoute
  '/catalog': typeof ProtectedDashboardCatalogRoute
  '/rooms': typeof ProtectedDashboardRoomsRoute
  '/room/$id': typeof ProtectedRoomIdRoute
  '/join/$code': typeof PublicJoinCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_protected/_dashboard': typeof ProtectedDashboardRouteRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_protected/_dashboard/catalog': typeof ProtectedDashboardCatalogRoute
  '/_protected/_dashboard/rooms': typeof ProtectedDashboardRoomsRoute
  '/_protected/room/$id': typeof ProtectedRoomIdRoute
  '/_public/join/$code': typeof PublicJoinCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/auth' | '/' | '/catalog' | '/rooms' | '/room/$id' | '/join/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/' | '/catalog' | '/rooms' | '/room/$id' | '/join/$code'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/auth'
    | '/_protected/_dashboard'
    | '/_public/'
    | '/_protected/_dashboard/catalog'
    | '/_protected/_dashboard/rooms'
    | '/_protected/room/$id'
    | '/_public/join/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/_dashboard': {
      id: '/_protected/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedDashboardRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_public/join/$code': {
      id: '/_public/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof PublicJoinCodeRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/room/$id': {
      id: '/_protected/room/$id'
      path: '/room/$id'
      fullPath: '/room/$id'
      preLoaderRoute: typeof ProtectedRoomIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/_dashboard/rooms': {
      id: '/_protected/_dashboard/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof ProtectedDashboardRoomsRouteImport
      parentRoute: typeof ProtectedDashboardRouteRoute
    }
    '/_protected/_dashboard/catalog': {
      id: '/_protected/_dashboard/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof ProtectedDashboardCatalogRouteImport
      parentRoute: typeof ProtectedDashboardRouteRoute
    }
  }
}

interface ProtectedDashboardRouteRouteChildren {
  ProtectedDashboardCatalogRoute: typeof ProtectedDashboardCatalogRoute
  ProtectedDashboardRoomsRoute: typeof ProtectedDashboardRoomsRoute
}

const ProtectedDashboardRouteRouteChildren: ProtectedDashboardRouteRouteChildren =
  {
    ProtectedDashboardCatalogRoute: ProtectedDashboardCatalogRoute,
    ProtectedDashboardRoomsRoute: ProtectedDashboardRoomsRoute,
  }

const ProtectedDashboardRouteRouteWithChildren =
  ProtectedDashboardRouteRoute._addFileChildren(
    ProtectedDashboardRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedDashboardRouteRoute: typeof ProtectedDashboardRouteRouteWithChildren
  ProtectedRoomIdRoute: typeof ProtectedRoomIdRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDashboardRouteRoute: ProtectedDashboardRouteRouteWithChildren,
  ProtectedRoomIdRoute: ProtectedRoomIdRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicJoinCodeRoute: typeof PublicJoinCodeRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicJoinCodeRoute: PublicJoinCodeRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
